server:
  servlet:
    context-path: /produdoro/api

springdoc:
  swagger-ui:
    path: /swagger

spring:
  data:
    mongodb:
      authentication-database: admin
      uri: ${MONGO_DB_URI:mongodb+srv://produdoro:Dev1234@cluster0.ypmcfaz.mongodb.net/test?retryWrites=true&w=majority}
      auto-index-creation: true


